name: Poetry Install Matrix

on:
  push:
    branches: '**'
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Setup
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version

    - name: Install dependencies
      run: |
        poetry install && poetry run pip install torch==2.2.1 torchaudio==2.2.1
